version: '3'
services:
  movies:
    image: nabeelj97/paytmappmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: nabeelj97/paytmapptrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: nabeelj97/paytmappdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: nabeelj97/paytmapprecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
