version: '3'
services:
  movies: nabeelj97/moviespaytm:latest
    image: 
    ports:
      - "90:80"
    deploy:
      replicas: 3
  train:
    image: nabeelj97/trainpaytm:latest
    ports:
      - "91:80"
    deploy:
      replicas: 3
  dth:
    image: nabeelj97/dthpaytm:latest
    ports:
      - "92:80"
    deploy:
      replicas: 3
  recharge:
    image: nabeelj97/rechargepaytm:latest
    ports:
      - "93:80"
    deploy:
      replicas: 3
